/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package DB;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;


/**
 *
 * @author Razan Alshaikh
 */
public class ShowAllCustomersUsingDB extends javax.swing.JFrame {

    /**
     * Creates new form ShowAllCustomersUsingDB
     */
    public ShowAllCustomersUsingDB() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TextArea = new javax.swing.JTextArea();

        jLabel2.setFont(new java.awt.Font("Helvetica Neue", 0, 30)); // NOI18N
        jLabel2.setText("Server Window");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 204, 204));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jPanel1.setBackground(new java.awt.Color(255, 204, 204));

        jLabel3.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        jLabel3.setText("Welcome Admin!");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Customers Information:");

        jButton1.setText("Display");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        TextArea.setColumns(20);
        TextArea.setRows(5);
        jScrollPane1.setViewportView(TextArea);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(121, 121, 121)
                        .addComponent(jLabel3))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(147, 147, 147)
                        .addComponent(jButton1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(49, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(jButton1)
                .addContainerGap(47, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            String text = printToTextArea();

            if (text.isEmpty()) {
                return;
            }

            TextArea.append("" + text + "\n");
        } catch (SQLException ex) {
            System.out.println("Exception in display all customers");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    private static Statement stat = null;
    public static Connection conn;

    public static void main(String[] args) throws ClassNotFoundException, SQLException {
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ShowAllCustomersUsingDB().setVisible(true);
            }
        });
        String URL = "jdbc:mysql://localhost:3306/salonapp?useSSL=false";
        String USERNAME = "C3A_3";
        String PASSWORD = "RJD@12345";
        try {
            conn = DriverManager.getConnection(URL, USERNAME, PASSWORD);
            stat = conn.createStatement();
            stat.executeUpdate("DROP TABLE customers");
            String creatTable = "CREATE TABLE customers( "
                    + " PhoneNo INT NOT NULL, "
                    + " password VARCHAR(45) NOT NULL, "
                    + "Fname VARCHAR(50) NOT NULL, "
                    + "Lname VARCHAR(50) NULL, "
                    + " address VARCHAR(50) NULL,"
                    + "email VARCHAR(50) NOT NULL,"
                    + "PRIMARY KEY (PhoneNo))";
            stat.executeUpdate(creatTable);
            String insertData = "INSERT INTO customers("
                    + "PhoneNo, password, Fname,Lname,address,email) VALUES "
                    + "('0549226961','Razan', 'Razan','Alshaikh','Alhamadaniyyah','Razan@hotmail.com'), "
                    + "('0551249415','Jana', 'Jana','Kurdi','alshati','jana@outlook.com'), "
                    + "('0500560751', 'Renad', 'Renad','Ghaleb','Almanar','Renad@gmail.com'), "
                    + "('0509447216', 'Noor', 'Noor','Babahr','noor','Noor@outlook.com')";
            stat.executeUpdate(insertData);

        } catch (Exception e) {
            System.out.println(" " + e.getMessage());
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea TextArea;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
public String printToTextArea() throws SQLException {
        String CustomersInfo=" ";
        try (ResultSet rs = stat.executeQuery("SELECT * FROM Customers")) {
            int i=1;
            
            while (rs.next()) {
                CustomersInfo += "Customer("+i+"): ";
                CustomersInfo += "Phone number: " + rs.getString("PhoneNo") + ", \n";
                CustomersInfo += "First name: " + rs.getString("Fname") + ", \n";
                CustomersInfo += "Last name: " + rs.getString("Lname") + ", \n";
                CustomersInfo += "Address: " + rs.getString("address") + ", \n";
                CustomersInfo += "Email: " + rs.getString("email");
                CustomersInfo += "\n";
                CustomersInfo += "#################\n";
                i++;
            }
            CustomersInfo+= " YOU HAVE  "+ --i +" CUSTOMERS! ";
        }
        return CustomersInfo;
    }

    public void close() {
        try {
            conn.close();
        } catch (SQLException ex) {
            System.out.println("Exception in close DB");
        }
    }
}
